-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 06:29:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responses` (
  `ResponseId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Temperature` DOUBLE NOT NULL,
  `CloseContact` VARCHAR(3) NOT NULL,
  `DateTimeSent` TEXT NOT NULL,
  PRIMARY KEY (`ResponseId`),
  UNIQUE INDEX `ResponseId_UNIQUE` (`ResponseId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`symptoms` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ResponseId` INT NOT NULL,
  `Symptom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `responseId1_idx` (`ResponseId` ASC) VISIBLE,
  CONSTRAINT `responseId1`
    FOREIGN KEY (`ResponseId`)
    REFERENCES `mydb`.`responses` (`ResponseId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
